info:
    version: ""
    title: data_source_huaweicloud_identitycenter_application_templates
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IdentityCenter
paths:
    /v1/application-templates:
        GET:
            tag: IdentityCenter
